### ISSUE TITLE
Выбрать асинхронный фреймворк для работы с Telegram bot API

### ISSUE THREAD

**Issue by digitalduke** [13th-floor/pythonrush_bot#6]
**Задача**: посмотреть какие есть годные асинхронные фреймворки для работы с Telegram bot API. Может все же есть какие-то альтернативы aiogram?

**Comment by ornichola** [comment]
На [сайте TG предлагаются](https://core.telegram.org/bots/samples) к использованию 3 фреймворка:
1. [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot). A wrapper you can't refuse.
2. [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI). Python Telegram Bot API.
3. [AIOGram](https://github.com/aiogram/aiogram). A pretty simple and fully asynchronous library for Telegram Bot API written with asyncio and aiohttp.

Асинхронный из них только AIOGram. У него большое [русскоязычное сообщество](https://t.me/aiogram_ru).

Помимо нашел еще несколько:
1. [pyrogram](https://github.com/pyrogram/pyrogram) - работает [с MTProto, а не с Bot API](https://docs.pyrogram.org/topics/mtproto-vs-botapi). Кажется, нам это не нужно.
2. [botogram](https://github.com/python-botogram/botogram) - не асинхронный. Давно существует, но обновления, судя по истории комитов, не частые. Некоторые тикеты [висят с 2016 года](https://github.com/python-botogram/botogram/issues).
3. [rocketgram](https://github.com/rocketgram/rocketgram) - асинхронный, [малопопулярный](https://github.com/rocketgram/rocketgram/network/dependents?package_id=UGFja2FnZS00MDE3MTE1NTQ%3D). Сообщество не обнаружил.
4. [telepot](https://github.com/nickoala/telepot) - поддержка завершена несколько лет назад.

Исходя из этого, кажется оптимальным вариантом остается AIOGram.

**Comment by digitalduke** [comment]
К aiogram у меня пока только одна претензия - местами никакая документация. Например, на самом "вкусном" месте https://docs.aiogram.dev/en/latest/dispatcher/webhook.html

Из интересного - у него есть I18n Middleware. Но у него я не нашел планировщика задач.

pyrogram вроде как неплох, с докой все в порядке, планировщик есть. Пока минус - похоже что для хранения стейта он использует sqlite. 

Посмотрю код aiogram и pyrogram, после этого обсудим что выбрать.

**Comment by digitalduke** [comment]
Из плюсов pyrogram - он должен быть быстрее https://docs.pyrogram.org/topics/mtproto-vs-botapi#what-is-the-bot-api

Так же у него есть некоторые интересные возможности, которые не получить через Bot API, например, _Retrieve the whole chat members list of either public or private chats_ и _Run multiple sessions at once, up to 10 per account (either bot or user)_

**Comment by digitalduke** [comment]
Обсудили возможные механики работы бота. Интереснее получается с использованием pyrogram. Попробуем его.
